apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: paper-fleet-autoscaler
spec:
  fleetName: my-game-fleet  # Should match fleet name
  policy:
    type: Webhook
    webhook:
      service:
        name: velocity-service
        path: /autoscale
        port: 7070  # Must match the config for Velocity Velagones
# Note: need one of these for each fleet!