apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocity-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velocity-role
rules: # Necessary permissions for Velagones to track the namespace
  - apiGroups: ["agones.dev"]
    resources: ["gameservers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velocity-binding
subjects:
  - kind: ServiceAccount
    name: velocity-sa
    namespace: game  # Make sure this matches!
roleRef:
  kind: Role
  name: velocity-role
  apiGroup: rbac.authorization.k8s.io