name: Velagones
version: 0.2.0
main: com.runicrealms.velagones.paper.VelagonesPlugin
api-version: '1.21.4'

permissions:
  velagones.command:
    description: Use /velagones admin subcommands
    default: op
